Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
l1 = Sol.listToListNode([7,2,4,3])
l2 = Sol.listToListNode([5,6,4])
l = Sol.addTwoNumbers(l1, l2)
print(Sol.ListNodeToList(l))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [2], line 1[0m
[0;32m----> 1[0m l1 [38;5;241m=[39m [43mSol[49m[38;5;241;43m.[39;49m[43mlistToListNode[49m([[38;5;241m7[39m,[38;5;241m2[39m,[38;5;241m4[39m,[38;5;241m3[39m])
[1;32m      2[0m l2 [38;5;241m=[39m Sol[38;5;241m.[39mlistToListNode([[38;5;241m5[39m,[38;5;241m6[39m,[38;5;241m4[39m])
[1;32m      3[0m l [38;5;241m=[39m Sol[38;5;241m.[39maddTwoNumbers(l1, l2)

[0;31mAttributeError[0m: 'Solution' object has no attribute 'listToListNode'
AttributeError: 'Solution' object has no attribute 'listToListNode'

